# Tambahkan GitHub Actions atau Jenkins
# .github/workflows/mlops-pipeline.yml

name: MLOps Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# workflows/mlops-pipeline.yml perlu diperbaiki
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Update version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r fastapibaru/requirements.txt
          pip install pytest pytest-cov
      - name: Run tests
        run: |
          cd fastapibaru
          python -m pytest tests/ -v --cov=app
      - name: Lint code
        run: |
          pip install flake8
          flake8 fastapibaru/app --max-line-length=120
  
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: |
          docker-compose up -d --build

