# Tambahkan GitHub Actions atau Jenkins
# .github/workflows/mlops-pipeline.yml
name: MLOps Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Model Tests
        run: |
          python -m pytest tests/
          python scripts/validate_model.py
  
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: |
          docker-compose up -d --build